# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BongDeoGee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BongDeoGee

  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'

end
